"""empty message

Revision ID: 48d44b854b40
Revises: 5fa9d8c55a2c
Create Date: 2019-07-02 12:24:47.163394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48d44b854b40'
down_revision = '5fa9d8c55a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crumbs', sa.Column('pseudocode', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('hide_demo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'hide_demo')
    op.drop_column('crumbs', 'pseudocode')
    # ### end Alembic commands ###
