"""hide_demo removed

Revision ID: 50ebf0341e72
Revises: 48d44b854b40
Create Date: 2019-07-02 12:29:41.264671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50ebf0341e72'
down_revision = '48d44b854b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'hide_demo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hide_demo', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
