"""Added a new column (imageUrl) to the user table

Revision ID: 5fa9d8c55a2c
Revises: 1a14077c59a9
Create Date: 2019-06-22 21:06:55.676663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fa9d8c55a2c'
down_revision = '1a14077c59a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('imageUrl', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'user', ['imageUrl'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'imageUrl')
    # ### end Alembic commands ###
